import json
import re
from datetime import datetime

from backend.config import REPORT_DIR
from backend.models.schemas import Finding


def _safe_name(value, fallback="unknown"):
    """Create a filesystem-safe name from a string."""

    value = str(value or "").strip()

    value = re.sub(
        r"[^A-Za-z0-9_-]+",
        "_",
        value,
    )

    value = value.strip("_")

    if not value:
        return fallback

    return value[:80]


def generate_report(
    scan_type: str,
    target: str,
    evidence: dict,
    findings: list[Finding],
    ai_analysis: str = "",
):
    """Generate a readable BADSHAH AI security assessment report."""

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    safe_scan_type = _safe_name(
        scan_type,
        fallback="scan",
    )

    safe_target = _safe_name(
        target,
        fallback="unknown_target",
    )

    directory = REPORT_DIR / safe_target

    directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    path = directory / (
        f"BADSHAH_AI_"
        f"{safe_scan_type}_"
        f"{timestamp}.txt"
    )

    lines = []

    lines.append("=" * 80)
    lines.append(
        "BADSHAH AI - SECURITY ASSESSMENT REPORT"
    )
    lines.append("=" * 80)

    lines.append(
        f"Scan Type : {scan_type}"
    )

    lines.append(
        f"Target    : {target}"
    )

    lines.append(
        f"Time      : {datetime.now().isoformat()}"
    )

    lines.append("")

    lines.append(
        "LOCAL SECURITY FINDINGS"
    )

    lines.append("-" * 80)

    if not findings:
        lines.append(
            "No findings were generated by the "
            "local rule-based assessment."
        )

    for number, finding in enumerate(
        findings,
        1,
    ):
        lines.extend(
            [
                "",
                f"[FINDING {number}]",
                f"Title       : {finding.title}",
                f"Severity    : {finding.severity}",
                "",
                "Description:",
                finding.description,
                "",
                "Impact:",
                finding.impact,
                "",
                "Evidence:",
            ]
        )

        for evidence_item in finding.evidence:
            lines.append(
                f"  - {evidence_item}"
            )

        lines.extend(
            [
                "",
                "Remediation:",
                finding.remediation,
                "",
                "Verification:",
                finding.verification,
                "",
            ]
        )

    lines.append(
        "AI SECURITY ANALYSIS"
    )

    lines.append("-" * 80)

    if ai_analysis:
        lines.append(
            ai_analysis.strip()
        )
    else:
        lines.append(
            "AI analysis was not generated."
        )

    lines.extend(
        [
            "",
            "RAW EVIDENCE",
            "-" * 80,
            json.dumps(
                evidence,
                indent=2,
                ensure_ascii=False,
                default=str,
            ),
            "",
            "=" * 80,
            "END OF REPORT",
            "=" * 80,
        ]
    )

    path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    return path
